In [1]:
import autosklearn.classification
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics
import pandas as pd
import os
import random

/home/mackenzie/anaconda3/lib/python3.7/site-packages/pyparsing.py:2725: FutureWarning: Possible set intersection at position 3
  self.re = re.compile( self.reString )
/home/mackenzie/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
X_train = pd.read_csv('/home/mackenzie/workspace/PycharmProjects/DAADRISE_AbusiveLangProject/dataFeatureSelected/ImportanceFeatures_300.csv')
y_train = pd.read_csv('/home/mackenzie/workspace/PycharmProjects/DAADRISE_AbusiveLangProject/dataFeatureSelected/TrainLabels.csv')
X_test = pd.read_csv('/home/mackenzie/workspace/PycharmProjects/DAADRISE_AbusiveLangProject/dataFeatureSelected/ImportanceFeaturesTest_300.csv')
y_test = pd.read_csv('/home/mackenzie/workspace/PycharmProjects/DAADRISE_AbusiveLangProject/dataFeatureSelected/TestLabels.csv')

In [3]:
print("start automl!")
automl = autosklearn.classification.AutoSklearnClassifier(time_left_for_this_task=3600, per_run_time_limit=360)
automl.fit(X_train, y_train, dataset_name='english_data') # feat_type=classification is another param we might use?
y_hat = automl.predict(X_test)

/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/automl.py:887: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Will change shape via np.ravel().
  y = self._check_y(y)


start automl!


/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)


[WARNING] [2019-07-18 13:30:56,827:EnsembleBuilder(1):english_data] No models better than random - using Dummy Score!
[WARNING] [2019-07-18 13:30:56,838:EnsembleBuilder(1):english_data] No models better than random - using Dummy Score!
[WARNING] [2019-07-18 13:30:58,841:EnsembleBuilder(1):english_data] No models better than random - using Dummy Score!
[WARNING] [2019-07-18 13:31:00,850:EnsembleBuilder(1):english_data] No models better than random - using Dummy Score!
[WARNING] [2019-07-18 13:31:02,855:EnsembleBuilder(1):english_data] No models better than random - using Dummy Score!
[WARNING] [2019-07-18 13:31:04,859:EnsembleBuilder(1):english_data] No models better than random - using Dummy Score!
[WARNING] [2019-07-18 13:31:06,863:EnsembleBuilder(1):english_data] No models better than random - using Dummy Score!


/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)


[WARNING] [2019-07-18 13:31:10,529:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2019-07-18 13:31:10,529:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger


/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/

/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/

/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/home/mackenzie/anaconda3/lib/python3.7/

1
['/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000000.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000001.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000002.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000003.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000004.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000005.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000006.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000007.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000008.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000009.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000010.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ensembles/1.0000000011.ensemble', '/tmp/autosklearn_tmp_990_6553/.auto-sklearn/ense

In [4]:
print("Accuracy Score:", sklearn.metrics.accuracy_score(y_test, y_hat))

Accuracy score 0.7746365105008077


In [5]:
automl.sprint_statistics() 

'auto-sklearn results:\n  Dataset name: english_data\n  Metric: accuracy\n  Best validation score: 0.774820\n  Number of target algorithm runs: 124\n  Number of successful target algorithm runs: 97\n  Number of crashed target algorithm runs: 12\n  Number of target algorithms that exceeded the time limit: 1\n  Number of target algorithms that exceeded the memory limit: 14\n'

In [6]:
# Create a new folder to hold statistics for a run
def createFolder(directory):
    try:
        if not os.path.exists(directory):
            os.makedirs(directory)
    except OSError:
        print ('Error: Creating directory. ' +  directory)

# create a random folder number to reference the directory
rand = random.randint(0, 1000)*random.randint(0,10)
directory = '/home/mackenzie/workspace/PycharmProjects/DAADRISE_AbusiveLangProject/TestResults/Test_' + str(rand)
print('The results for this run will be stored in ' + directory)
createFolder(directory)

The results for this run will be stored in /home/mackenzie/workspace/PycharmProjects/DAADRISE_AbusiveLangProject/TestResults/Test_4446


In [7]:
# Saves the cv results to a csv in the folder specified
results = automl.cv_results_ #A dict with keys as column headers and values as columns, 
                             #that can be imported into a pandas DataFrame

# dict --> pandas dataframe
cv_results = pd.DataFrame.from_dict(results)
print('CV Results partially shown below')
print(cv_results.head())
cv_results.to_csv(directory+'/cv_results.csv')

   mean_test_score  mean_fit_time  \
0         0.770843      10.024223   
1         0.000000       0.717020   
2         0.736729      13.601961   
3         0.000000       1.613386   
4         0.000000     360.099214   

                                              params  rank_test_scores  \
0  {'balancing:strategy': 'none', 'categorical_en...                53   
1  {'balancing:strategy': 'weighting', 'categoric...                98   
2  {'balancing:strategy': 'weighting', 'categoric...                62   
3  {'balancing:strategy': 'weighting', 'categoric...                98   
4  {'balancing:strategy': 'weighting', 'categoric...                98   

    status param_balancing:strategy param_categorical_encoding:__choice__  \
0  Success                     none                      one_hot_encoding   
1   Memout                weighting                      one_hot_encoding   
2  Success                weighting                      one_hot_encoding   
3    Crash              

In [8]:
# Saves the model info to the directory specified
models = automl.get_models_with_weights() # Return a list of the final ensemble found by auto-sklearn.
model_info = pd.DataFrame.from_dict([models[0], models[1], models[2], models[3], models[4], models[5], models[6], models[7],
                            models[8], models[9], models[10], models[11]])
model_info.to_csv(directory+'/model_info.csv')
print('Model Results partially shown below')
print(models)

[(0.14, SimpleClassificationPipeline({'balancing:strategy': 'none', 'categorical_encoding:__choice__': 'one_hot_encoding', 'classifier:__choice__': 'lda', 'imputation:strategy': 'mean', 'preprocessor:__choice__': 'no_preprocessing', 'rescaling:__choice__': 'standardize', 'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False', 'classifier:lda:n_components': 247, 'classifier:lda:shrinkage': 'auto', 'classifier:lda:tol': 0.007036258092678278},
dataset_properties={
  'task': 2,
  'sparse': False,
  'multilabel': False,
  'multiclass': True,
  'target_type': 'classification',
  'signed': False})), (0.1, SimpleClassificationPipeline({'balancing:strategy': 'weighting', 'categorical_encoding:__choice__': 'one_hot_encoding', 'classifier:__choice__': 'sgd', 'imputation:strategy': 'median', 'preprocessor:__choice__': 'nystroem_sampler', 'rescaling:__choice__': 'standardize', 'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False', 'classifier:sgd:alpha': 0.02052955505

In [10]:
print("Confusion Matrix: ")
print(sklearn.metrics.confusion_matrix(y_test, y_hat))

Confusion Matrix: 
[[   0  285    0]
 [   0 3836    0]
 [   0  831    0]]
